### ISSUE TITLE
Cleanup jx-boot jobs?

### ISSUE THREAD

**Issue by gazal-k** [jenkins-x/jx-git-operator#146]
In particularly busy automatic Env/GitOps repos, the number of `jx-boot` jobs can keep growing. I'm not sure if this is even a major problem, perhaps something to consider.

I suppose we can set `ttlSecondsAfterFinished` on the `Job`. But the feature [TTLAfterFinished](https://kubernetes.io/docs/concepts/workloads/controllers/ttlafterfinished/) seems to still be in alpha.

Another option is to add some cleanup logic into the operator itself to only keep like the latest `n` jobs. `n` can be like an opt-in config from the chart.

**Comment by tomhobson** [comment]
First stage: https://github.com/jenkins-x-plugins/jx-gitops/pull/824

We're going to add it to the default cronjobs soon

**Comment by msvticket** [comment]
Closing as fixed
