### ISSUE TITLE
googleapis charts jx3 403 forbidden

### ISSUE THREAD

**Issue by matiasgonzalocalvo** [jenkins-x/jx-git-operator#192]
MBRU309734:jx3-openshift a309734$ /Users/a309734/.jx3/plugins/bin/helm-3.6.2   repo add jx3 https://storage.googleapis.com/jenkinsxio/charts
Error: looks like "https://storage.googleapis.com/jenkinsxio/charts" is not a valid chart repository or cannot be reached: failed to fetch https://storage.googleapis.com/jenkinsxio/charts/index.yaml : 403 Forbidden

**Comment by pintomic** [comment]
According to this Jenkins X [blog post](https://jenkins-x.io/blog/2021/08/26/moving-v2-artifacts/) 
> Jenkins X specific helm repositories and container registries hosted on GCP have been moved to GitHub:
> https://storage.googleapis.com/jenkinsxio/charts
> has been moved to
> https://jenkins-x-charts.github.io/repo

**Comment by matiasgonzalocalvo** [comment]
fix: jx upgrade cli --version 3.2.192
