### ISSUE TITLE
Dockerfile for ghcr.io/jenkins-x/jx-boot

### ISSUE THREAD

**Issue by rochanaatapattu** [jenkins-x/jx-git-operator#206]
Hi,

Where can I find the dockerfile used in the boot job.
Also any easy ways to add extended jx cli plugins to the boot job.

Thank you,
Rochana

**Comment by joshuasimon-taulia** [comment]
i think this is it https://github.com/jenkins-x/jx/blob/main/Dockerfile-boot

**Comment by msvticket** [comment]
Yes, it is
