### ISSUE TITLE
Repository not found

### ISSUE THREAD

**Issue by peter-poki** [jenkins-x/jx-git-operator#39]
Hello guys,

testing jx3 version, and when I want to install operator, it fails, probably by :
```
lets ignore commit errors in case there's no changes and to stop pipelines failing
git commit -m "chore: regenerated"
[master 0b66fc6] chore: regenerated
 16 files changed, 145 insertions(+), 11 deletions(-)
 create mode 100644 config-root/namespaces/jx/lighthouse-config/config-cm.yaml
 create mode 100644 config-root/namespaces/jx/lighthouse-config/plugins-cm.yaml
git push
remote: Repository not found.
fatal: repository 'https://peter-poki:MY_TOKEN_GENERATED@github.com/myorg-tst/jx3-demo4/' not found
make[1]: Leaving directory '/workspace/source'
make[1]: *** [versionStream/src/Makefile.mk:197: push] Error 128
error: failed to run make verify-ingress-ignore all verify-ignore secrets-populate commit push secrets-wait: failed to run 'make verify-ingress-ignore all verify-ignore secrets-populate commit push secrets-wait' command in directory '', output: ''
make: *** [versionStream/src/Makefile.mk:154: regen-check] Error 1
boot Job pod jx-boot-c42508f637c197fc0ed65ba-kbkgv has Failed
```

It seems, that everything is ready, cluster seems to have all pods, environments, etc. but git operator fails. If I open url in browser https://peter-poki:MY_TOKEN_GENERATED@github.com/myorg-tst/jx3-demo4/, then I get some error,  **Failed to load latest commit information.**  But when I open repository in second tab, where I am looged in normally (not withou token in url), it works without this message.
![image](https://user-images.githubusercontent.com/22402252/93054752-20792d00-f66a-11ea-94ad-5119294aad97.png)

At the beggining of the installation, it validates MY_TOKEN_GENERATED:
`
git username is peter-poki for URL https://github.com/myorg-tst/jx3-demo4 and we have a valid password
`

jx version  
`     
version: 3.0.248
`

Any ideas?

Thanks for help.

**Comment by jstrachan** [comment]
wonder if github was having issues when you tried running the operator? does running it again help?

**Comment by peter-poki** [comment]
Hi, in the newer version it seems to be working without any problem, closing the issue.

Thanks!
